const bookings = [
    {
        id: 1,
        bookingDate: "2021-11-30",
        guest: true,
        guestName: "Jan Kowalski",
        status: true,
        statusSetDate: "2021-11-09",
        deleted: false,
        bookingUserName: "Katarzyna Wujec",
        acceptOperatorName: "-",
        deskNumber: "IT1.1",
        userName: "-",
        office: "IT1",
    },
    {
        id: 2,
        bookingDate: "2021-12-31",
        guest: false,
        guestName: null,
        status: null,
        statusSetDate: null,
        deleted: false,
        bookingUserName: "Mariusz Wasilewski",
        acceptOperatorName: "Mariusz Wasilewski",
        deskNumber: "IT4.5",
        userName: "Mariusz Wasilewski",
        office: "IT4",
    },
    {
        id: 3,
        bookingDate: "2021-11-30",
        guest: false,
        guestName: null,
        status: true,
        statusSetDate: "2021-11-15",
        deleted: false,
        bookingUserName: "Agnieszka Hewusz",
        acceptOperatorName: "Agnieszka Hewusz",
        deskNumber: "IT4.5",
        userName: "Agnieszka Hewusz",
        office: "IT4",
    },
];

export const MockBookings = () => Promise.resolve(bookings);