const desks = [
    {
        id: 1,
        name: "Pierwsze",
        regulation: false,
        numberOfMonitors: 1,
        description: "",
        deleted: false,
        desk: "IT1.1",
        office: "IT1",
    },
    {
        id: 2,
        name: "Drugie",
        regulation: false,
        numberOfMonitors: 1,
        description: "",
        deleted: false,
        desk: "IT1.2",
        office: "IT1",
    },
    {
        id: 3,
        name: "Trzecie",
        regulation: false,
        numberOfMonitors: 1,
        description: "",
        deleted: false,
        desk: "IT1.3",
        office: "IT1",
    },
    {
        id: 4,
        name: "Szef",
        regulation: false,
        numberOfMonitors: 1,
        description: "",
        deleted: false,
        desk: "IT2",
        office: "IT2",
    },
    {
        id: 5,
        name: "Pierwsze",
        regulation: false,
        numberOfMonitors: 1,
        description: "",
        deleted: false,
        desk: "IT3.1",
        office: "IT3",
    },
    {
        id: 6,
        name: "Drugie",
        regulation: false,
        numberOfMonitors: 1,
        description: "",
        deleted: false,
        desk: "IT3.2",
        office: "IT3",
    },
    {
        id: 7,
        name: "Trzecie",
        regulation: false,
        numberOfMonitors: 1,
        description: "",
        deleted: false,
        desk: "IT3.3",
        office: "IT3",
    },
    {
        id: 8,
        name: "Michal",
        regulation: false,
        numberOfMonitors: 2,
        description: "",
        deleted: false,
        desk: "IT4.1",
        office: "IT4",
    },
    {
        id: 9,
        name: "Piotr",
        regulation: false,
        numberOfMonitors: 2,
        description: "",
        deleted: false,
        desk: "IT4.2",
        office: "IT4",
    },
    {
        id: 10,
        name: "Lukasz",
        regulation: false,
        numberOfMonitors: 2,
        description: "",
        deleted: false,
        desk: "IT4.3",
        office: "IT4",
    },
    {
        id: 11,
        name: "Filip",
        regulation: true,
        numberOfMonitors: 2,
        description: "",
        deleted: false,
        desk: "IT4.4",
        office: "IT4",
    },
    {
        id: 12,
        name: "Pawel",
        regulation: true,
        numberOfMonitors: 2,
        description: "",
        deleted: false,
        desk: "IT4.5",
        office: "IT4",
    },
];

export const MockDesks = () => Promise.resolve(desks);